// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package storedb

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (text)
VALUES ($1)
RETURNING id, text
`

func (q *Queries) CreateTask(ctx context.Context, text string) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, text)
	var i Task
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
SELECT id, text
FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, text
FROM tasks
ORDER BY text ASC, id ASC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(&i.ID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
